### ISSUE TITLE
Stolen Name

### ISSUE THREAD

**Issue by JH456** [kpberry/command-line-sweeper#1]
You stole this name. Please pay me 57 BTC for ownership rights. Thx.

**Comment by kpberry** [comment]
no thx

**Comment by JH456** [comment]
pls

**Comment by kpberry** [comment]
pls no

**Comment by JH456** [comment]
no pls

**Comment by JH456** [comment]
# we're not done here

**Comment by JH456** [comment]
# YOU CAN'T JUST SHUT OFF THE WORLD

**Comment by JH456** [comment]
# **I WILL NOT BE SILENCED**

**Comment by kpberry** [comment]
i linked to your website what more do you want jam

**Comment by kpberry** [comment]
and don't say 57 btc

**Comment by JH456** [comment]
Oh, oh no the price has gone up now

**Comment by JH456** [comment]
I want $10 million

**Comment by JH456** [comment]
And a helicopter
